### ISSUE TITLE
Owoifier doesn't install

### ISSUE THREAD

**Issue by Mistabay** [powercord-community/owoifier#10]
Once i paste the command in cmd, and restart discord, nothing happens.
Here's a video where my issue is shown: https://youtu.be/85Bn03A4Xlc (Sorry for russian system language)

**Comment by Fezalion** [comment]
You have to clone the plugin into your plugins folder, if you have installed powercord to the default location, you can just use `cd powercord/src/Powercord/plugins && git clone https://github.com/powercord-community/owoifier.git` , then restart your Discord.

**Comment by Mistabay** [comment]
Thanks, that worked
