### ISSUE TITLE
Toggleowo owoifies commands.

### ISSUE THREAD

**Issue by ghost** [powercord-community/owoifier#7]
If you enable the plugin and try to turn it off the command wont work because it owoifies the command too, you can still turn it off in the settings so its not too bad.

**Comment by Fezalion** [comment]
I can't seem to be able to replicate, to be sure, are we talking about the `toggleowo` command here, it seems to work fine on my end.

**Comment by Fezalion** [comment]
![OMNV0qJLvl](https://user-images.githubusercontent.com/14075907/114180446-de3a7480-9948-11eb-956b-c551eedb81d4.gif)

**Comment by ghost** [comment]
https://media.discordapp.net/attachments/827670335947931659/830062642621710346/owoify-broken.gif
I hope this explains a bit better whats happening

**Comment by Fezalion** [comment]
I added a toggle in the plugin settings to toggle auto owoify, I still can't replicate the issue on my end, but for now button in the settings should help with this issue. [commit](https://github.com/powercord-community/owoifier/commit/a3a6964172978f857c359605bb7b995513267d07)

**Comment by Fezalion** [comment]
Should be fixed with [commit](https://github.com/powercord-community/owoifier/commit/eaf0b72bc0438c0d6345a1dae13399502c880e4a).

**Comment by Fezalion** [comment]
Apperently not fixed yet, issue is plugin loads before powercords command handler (which is not the case for everybody ?), so input gets owoified before command handler can handle the command, needs further investigation so I'm reopening the issue.
